/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author rmibord
 */
public class ChoixBateau extends javax.swing.JFrame {

    private JPanel imagePanel;
    private JLabel imageLabel;
    private JComboBox<String> comboBox;
    private Map<String, ImageIcon> imageMap;
    
    public ChoixBateau() {
        initComponents();
        customInit();
        this.setTitle("Boat Rush");
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.BLUE);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BoatRush");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choisissez votre navire");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InterfaceJeu fenetre = new InterfaceJeu();
        fenetre.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    */
    private void customInit() {
        // Initialize the image map
        this.setLayout(new BorderLayout());
        imageMap = new HashMap<>();
        imageMap.put("Green Boat", new ImageIcon("Z:/Mes documents/Informatique/BoatRush/BoatRush/src/resources/GreenBoat.png"));
        imageMap.put("Green Yacht", new ImageIcon("Z:/Mes documents/Informatique/BoatRush/BoatRush/src/resources/GreenYacht.png"));
        imageMap.put("Brown Boat", new ImageIcon("Z:/Mes documents/Informatique/BoatRush/BoatRush/src/resources/BrownBoat.png"));
        imageMap.put("Brown Yacht", new ImageIcon("Z:/Mes documents/Informatique/BoatRush/BoatRush/src/resources/BrownYacht.png"));
        imageMap.put("Purple Boat", new ImageIcon("Z:/Mes documents/Informatique/BoatRush/BoatRush/src/resources/PurpleBoat.png"));
        imageMap.put("Purple Yacht", new ImageIcon("Z:/Mes documents/Informatique/BoatRush/BoatRush/src/resources/PurpleYacht.png"));
        

        // Initialize and configure the JComboBox
        comboBox = new JComboBox<>(imageMap.keySet().toArray(new String[0]));
        comboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateImage((String) comboBox.getSelectedItem());
            }
        });

        // Initialize the JPanel and JLabel for the image
        imagePanel = new JPanel();
        imageLabel = new JLabel();
        imagePanel.add(imageLabel);

        // Add components to the JFrame
        this.setLayout(null);
        
        comboBox.setBounds(250, 130, 100, 30);
        imagePanel.setBounds(200, 200, 200, 120); 

        this.add(comboBox);
        this.add(imagePanel);

        // Show the default image
        if (!imageMap.isEmpty()) {
            updateImage((String) comboBox.getSelectedItem());
        }
    }

    private void updateImage(String selectedItem) {
        // Update the JLabel with the corresponding image
        ImageIcon icon = imageMap.get(selectedItem);
        if (icon != null) {
            imageLabel.setIcon(icon);
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            ChoixBateau frame = new ChoixBateau();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(600, 500);
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
